<a href="https://colab.research.google.com/github/aruphar/Pytorch_Practice/blob/main/PytorchPractice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
my_list = [[1,2,3,4],[5,6,7,8]]
my_list


[[1, 2, 3, 4], [5, 6, 7, 8]]

**NUMPY ARRAYS**

In [7]:
import numpy as np
#Creating numpy array using arange
my_numpy_array = np.arange(15)
my_numpy_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
#Creating numpy array using numpy.array()
my_numpy_array1 = np.array([[1,2,3],[4,5,6]])
my_numpy_array1


array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
#Creating numpy array using random.rand()
my_numpy_array2 = np.random.rand(3,4,5)
print(my_numpy_array2, my_numpy_array2.dtype)

[[[0.78952811 0.63604548 0.21413286 0.93552606 0.62704508]
  [0.47523412 0.23148529 0.36599776 0.36064878 0.83412398]
  [0.39589496 0.92545061 0.01729008 0.67237598 0.8031861 ]
  [0.32392932 0.47118066 0.48549597 0.91073008 0.65295266]]

 [[0.17820154 0.0695335  0.97293569 0.34077444 0.34128173]
  [0.14365865 0.47066612 0.62444197 0.66139811 0.9076708 ]
  [0.57048696 0.45658006 0.55009518 0.60383268 0.54090644]
  [0.65416046 0.00455829 0.99544075 0.53200612 0.92964463]]

 [[0.30584891 0.32452921 0.5391911  0.76331378 0.73137633]
  [0.58962259 0.10832509 0.54477443 0.76816631 0.90118302]
  [0.5491321  0.34293974 0.02198774 0.36642896 0.79746335]
  [0.3764389  0.57222103 0.01544479 0.76786958 0.48534356]]] float64


**TENSORS**

In [23]:
import torch
#Creating tensor using torch.randn()
tensor_1 = torch.randn(3,4)
print(tensor_1, tensor_1.dtype)


tensor([[-0.3054,  0.0164, -0.4369,  0.9629],
        [-0.0348,  1.1237, -1.4176,  1.5097],
        [ 1.0358,  1.1049, -1.5514, -0.6001]]) torch.float32


In [26]:
#Creating tensor from numpy array
tensor_2 = torch.tensor(my_numpy_array2)
tensor_2

tensor([[[0.7895, 0.6360, 0.2141, 0.9355, 0.6270],
         [0.4752, 0.2315, 0.3660, 0.3606, 0.8341],
         [0.3959, 0.9255, 0.0173, 0.6724, 0.8032],
         [0.3239, 0.4712, 0.4855, 0.9107, 0.6530]],

        [[0.1782, 0.0695, 0.9729, 0.3408, 0.3413],
         [0.1437, 0.4707, 0.6244, 0.6614, 0.9077],
         [0.5705, 0.4566, 0.5501, 0.6038, 0.5409],
         [0.6542, 0.0046, 0.9954, 0.5320, 0.9296]],

        [[0.3058, 0.3245, 0.5392, 0.7633, 0.7314],
         [0.5896, 0.1083, 0.5448, 0.7682, 0.9012],
         [0.5491, 0.3429, 0.0220, 0.3664, 0.7975],
         [0.3764, 0.5722, 0.0154, 0.7679, 0.4853]]], dtype=torch.float64)

In [38]:
#Creating tensors with all ones or zeroes.
tensor_4 = torch.ones([5,4,3], dtype=torch.int32)
tensor_5 = torch.zeros([7,3,2], dtype=torch.int32)
print(tensor_4)
print(tensor_5)

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]], dtype=torch.int32)
tensor([[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]], dtype=torch.int32)


In [51]:
print("Shape of tensor_4 = ", tensor_4.shape,"Shape of tensor_5 = ",  tensor_5.shape)
print("Layout of tensor_4 = ", tensor_4.layout,"Layout of tensor_5 = ",  tensor_5.layout)
print("Stride of tensor_4 = ", tensor_4.stride(), "Stride of tensor_5 = ", tensor_5.stride())



Shape of tensor_4 =  torch.Size([5, 4, 3]) Shape of tensor_5 =  torch.Size([7, 3, 2])
Layout of tensor_4 =  torch.strided Layout of tensor_5 =  torch.strided
Stride of tensor_4 =  (12, 3, 1) Stride of tensor_5 =  (6, 2, 1)


In [55]:
tensor_6 = torch.randn(2,3)
tensor_7 = tensor_6.t()
print(tensor_6, "; shape of tensor_6 = ", tensor_6.shape, "; stride of tensor_6 = ", tensor_6.stride())
print(tensor_7, "; shape of tensor_7 = ", tensor_7.shape, "; stride of tensor_7 = ", tensor_7.stride())

tensor([[-0.3327, -0.4107,  1.4686],
        [ 0.3328, -0.1958,  1.8847]]) ; shape of tensor_6 =  torch.Size([2, 3]) ; stride of tensor_6 =  (3, 1)
tensor([[-0.3327,  0.3328],
        [-0.4107, -0.1958],
        [ 1.4686,  1.8847]]) ; shape of tensor_7 =  torch.Size([3, 2]) ; stride of tensor_7 =  (1, 3)
