<a href="https://colab.research.google.com/github/aruphar/Pytorch_Practice/blob/main/PytorchPractice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
# Reshaping if we don't know the number of items
# using -1
my_torch2 = torch.arange(10)
print(f"my_torch2 : \n{my_torch2}")

my_torch2 = my_torch2.reshape(5,-1)
print(f"\nAfter reshaping with (5,-1)\n{my_torch2}")

my_torch2 = my_torch2.reshape(-1,5)
print(f"\nAfter reshaping with (-1,5)\n{my_torch2}")

my_torch2 : 
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

After reshaping with (5,-1)
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

After reshaping with (-1,5)
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [16]:
# Using View
my_torch3 = torch.arange(10)
print(f"my_torch3 = \n{my_torch3}")

my_torch3 = my_torch3.view(2,5)
print(f"\nAfter using view = \n{my_torch3}")

my_torch3 = 
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

After using view = 
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


**When making a new tensor from an existing tensor with reshape or view**
**if we make a change in one tensor, the other will also get updated**

In [30]:
my_torch4 = torch.arange(10)
print(my_torch4)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [31]:
my_torch5 = my_torch4.reshape(2,-1)
my_torch5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [32]:
# After reshaping my_torch4, check my_torch4 and my_torch5
my_torch4[1] = 4141
print(f"my_torch4 = \n{my_torch4}")
print(f"\nmy_torch5 = \n{my_torch5}")

my_torch4 = 
tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

my_torch5 = 
tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


In [33]:
# After reshaping my_torch5, check my_torch4 and my_torch5
my_torch5[1][1] = 1000
print(f"my_torch4 = \n{my_torch4}")
print(f"\nmy_torch5 = \n{my_torch5}")

my_torch4 = 
tensor([   0, 4141,    2,    3,    4,    5, 1000,    7,    8,    9])

my_torch5 = 
tensor([[   0, 4141,    2,    3,    4],
        [   5, 1000,    7,    8,    9]])


**Slicing**
Allows us to grab a section of the tensor

**The use of ":" indicates that we want to include all elements along a particular dimension**

**number : -> Exclude everything before number then include**

**: number -> Include everything before number then exclude**

In [41]:
my_torch6 = torch.arange(10)
print(f"my_torch6 = \n{my_torch6}")

#Grab a specific item
print(f"\nGrabbing 8th element of my_torch6 : \n{my_torch6[7]}")
my_torch6[7]

#Grab a specific slice
my_torch7 = my_torch6.reshape(5,2)
print(f"\nmy_torch7 = \n{my_torch7}")

print(f"\nGrabbing a slice of my_torch 7 :\n")
my_torch7[:,1]

#Return Column
print(f"Printing it as a column")
my_torch7[:,1:]

my_torch6 = 
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Grabbing 8th element of my_torch6 : 
7

my_torch7 = 
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

Grabbing a slice of my_torch 7 :

Printing it as a column


tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [57]:
my_torch8 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(f"my_torch8")
print(my_torch8)

#Slice the first row
row_slice = my_torch8[0,:]
print(f"\nRow_slice [0,:] -> \n{row_slice}")

#Slice the first column
column_slice = my_torch8[:,0]
print(f"\ncolumn_slice [:,0] -> \n{column_slice}")

#Slice a submatrix
submatrix_slice1 = my_torch8[1:,1:]
print(f"\nsubmatrix_slice1 [1:,1:] -> \n{submatrix_slice1}")

submatrix_slice2 = my_torch8[:1,:1]
print(f"\nsubmatrix_slice2 [:1,:1] -> \n{submatrix_slice2}")

submatrix_slice3 = my_torch8[0:,0:]
print(f"\nsubmatrix_slice3 [0:,0:] -> \n{submatrix_slice3}")

submatrix_slice4 = my_torch8[:0,:0]
print(f"\nsubmatrix_slice4 [:0,:0] -> \n{submatrix_slice4}")

my_torch8
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Row_slice [0,:] -> 
tensor([1, 2, 3])

column_slice [:,0] -> 
tensor([1, 4, 7])

submatrix_slice1 [1:,1:] -> 
tensor([[5, 6],
        [8, 9]])

submatrix_slice2 [:1,:1] -> 
tensor([[1]])

submatrix_slice3 [0:,0:] -> 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

submatrix_slice4 [:0,:0] -> 
tensor([], size=(0, 0), dtype=torch.int64)


**Joining Tensors**
When you want to combine multiple tensors, you’ll primarily use torch.cat or torch.stack. The difference is subtle but crucial.

**torch.cat (Concatenate)**
This joins tensors along an existing dimension. The tensors must have the same shape except in the dimension you are concatenating.

**---- Best for: Adding more rows to a matrix or more channels to an image.**

**torch.stack**
This joins tensors along a new dimension. It’s like taking three 2D sheets of paper and stacking them to create a 3D book.

**---- Best for: Creating a "batch" dimension from individual samples.**

In [64]:
# Joining using cat
# Create two tensors
x = torch.randn(2,3)
y = torch.randn(2,3)
print(f"tensor x = \n{x}")
print(f"tensor y = \n{y}")

cat_tensor1 = torch.cat((x,y), dim = 0)
cat_tensor2 = torch.cat((x,y), dim = 1)

print(f"\nConcatenated Tensor 1 with dim 0 i.e. row-wise\n{cat_tensor1}")
print(f"\nConcatenated Tensor 2 with dim 1 i.e. col-wise\n{cat_tensor2}")

tensor x = 
tensor([[-1.7931,  1.0579,  0.6976],
        [-0.8433,  0.3800, -0.4132]])
tensor y = 
tensor([[ 0.9385, -1.1827,  0.7294],
        [ 0.2005,  0.7482, -0.4333]])

Concatenated Tensor 1 with dim 0 i.e. row-wise
tensor([[-1.7931,  1.0579,  0.6976],
        [-0.8433,  0.3800, -0.4132],
        [ 0.9385, -1.1827,  0.7294],
        [ 0.2005,  0.7482, -0.4333]])

Concatenated Tensor 2 with dim 1 i.e. col-wise
tensor([[-1.7931,  1.0579,  0.6976,  0.9385, -1.1827,  0.7294],
        [-0.8433,  0.3800, -0.4132,  0.2005,  0.7482, -0.4333]])


In [65]:
# Joining using stack
# Create two tensors
x = torch.randn(2,3)
y = torch.randn(2,3)
print(f"tensor x = \n{x}")
print(f"tensor y = \n{y}")

stacked_tensor1 = torch.stack((x,y), dim = 0)
stacked_tensor2 = torch.stack((x,y), dim = 1)

print(f"\nStacked Tensor 1 with dim 0 i.e. row-wise\n{stacked_tensor1}")
print(f"\nStacked Tensor 2 with dim 1 i.e. col-wise\n{stacked_tensor2}")

tensor x = 
tensor([[-0.8770, -1.4346, -1.7364],
        [-1.4323, -1.3403,  0.9128]])
tensor y = 
tensor([[ 1.0379,  0.4479, -0.8323],
        [ 0.7469,  0.7245,  0.5646]])

Stacked Tensor 1 with dim 0 i.e. row-wise
tensor([[[-0.8770, -1.4346, -1.7364],
         [-1.4323, -1.3403,  0.9128]],

        [[ 1.0379,  0.4479, -0.8323],
         [ 0.7469,  0.7245,  0.5646]]])

Stacked Tensor 2 with dim 1 i.e. col-wise
tensor([[[-0.8770, -1.4346, -1.7364],
         [ 1.0379,  0.4479, -0.8323]],

        [[-1.4323, -1.3403,  0.9128],
         [ 0.7469,  0.7245,  0.5646]]])


In [81]:
# Splitting using split
# Create a new tensor
x = torch.randn(5, 3)
print(f"tensor x = \n{x}")

# splitting into 2 chunks row-wise(along dim 0)
chunks = torch.chunk(x, 2, dim = 0)
print(f"\nSplit row-wise into two chunks = ")
print(f"\nchunks[0] = \n{chunks[0]}]")
print(f"\nchunks[1] = \n{chunks[1]}]")

# splitting into 3 chunks row-wise(along dim 0)
chunks = torch.chunk(x, 3, dim = 0)
print(f"\nSplit row-wise into three chunks = ")
print(f"\nchunks[0] = \n{chunks[0]}]")
print(f"\nchunks[1] = \n{chunks[1]}]")
print(f"\nchunks[2] = \n{chunks[2]}]")

# splitting into 2 chunks col-wise(along dim 1)
chunks = torch.chunk(x, 2, dim = 1)
print(f"\nSplit col-wise into tow chunks = ")
print(f"\nchunks[0] = \n{chunks[0]}]")
print(f"\nchunks[1] = \n{chunks[1]}]")

tensor x = 
tensor([[ 1.3161, -1.6650, -1.6504],
        [ 1.4777, -1.7157,  0.5283],
        [-0.6852, -0.6735, -1.1775],
        [-0.5384,  1.8780,  0.6198],
        [-0.2812,  0.4426, -1.5190]])

Split row-wise into two chunks = 

chunks[0] = 
tensor([[ 1.3161, -1.6650, -1.6504],
        [ 1.4777, -1.7157,  0.5283],
        [-0.6852, -0.6735, -1.1775]])]

chunks[1] = 
tensor([[-0.5384,  1.8780,  0.6198],
        [-0.2812,  0.4426, -1.5190]])]

Split row-wise into three chunks = 

chunks[0] = 
tensor([[ 1.3161, -1.6650, -1.6504],
        [ 1.4777, -1.7157,  0.5283]])]

chunks[1] = 
tensor([[-0.6852, -0.6735, -1.1775],
        [-0.5384,  1.8780,  0.6198]])]

chunks[2] = 
tensor([[-0.2812,  0.4426, -1.5190]])]

Split col-wise into tow chunks = 

chunks[0] = 
tensor([[ 1.3161, -1.6650],
        [ 1.4777, -1.7157],
        [-0.6852, -0.6735],
        [-0.5384,  1.8780],
        [-0.2812,  0.4426]])]

chunks[1] = 
tensor([[-1.6504],
        [ 0.5283],
        [-1.1775],
        [ 0.6198],